# Generated by Django 5.1.6 on 2026-04-01 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ERROR_500', 'Erreur 500'), ('SYNC_FAILURE', 'Échec synchronisation'), ('HIGH_RESPONSE_TIME', 'Temps de réponse élevé'), ('STORAGE_FULL', 'Stockage plein'), ('BACKUP_FAILED', 'Sauvegarde échouée'), ('SUBSCRIPTION_EXPIRED', 'Abonnement expiré')], max_length=30)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_alerts', to='superadmin.tenant')),
            ],
            options={
                'verbose_name': 'Alerte système',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Ex: student_created, grade_validated', max_length=200)),
                ('entity_type', models.CharField(help_text='Ex: Student, Grade, Enrollment', max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='superadmin.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'timestamp'], name='monitoring__tenant__3a20da_idx'), models.Index(fields=['entity_type', 'entity_id'], name='monitoring__entity__e52073_idx')],
            },
        ),
    ]
