# Generated by Django 5.1.6 on 2026-06-30 23:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0008_subscription_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('priority', models.IntegerField(choices=[(0, 'PAYMENT'), (1, 'ATTENDANCE'), (2, 'GRADE'), (3, 'MESSAGE')], default=2)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('local_version', models.IntegerField()),
                ('server_version', models.IntegerField()),
                ('resolution', models.CharField(choices=[('PENDING', 'Pending'), ('SERVER_WINS', 'Server Wins'), ('CLIENT_WINS', 'Client Wins'), ('MANUAL', 'Manual')], default='PENDING', max_length=20)),
                ('server_data', models.JSONField(blank=True, default=dict)),
                ('client_data', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conflict', to='sync.syncqueueitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
