# Generated by Django 5.1.6 on 2026-04-01 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedagogy', '0001_initial'),
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('TUITION', 'Scolarité'), ('REGISTRATION', 'Inscription'), ('CANTEEN', 'Cantine'), ('TRANSPORT', 'Transport'), ('UNIFORM', 'Uniforme'), ('SUPPLIES', 'Fournitures'), ('TRIP', 'Sortie scolaire'), ('OTHER', 'Autre')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installments', models.JSONField(blank=True, default=list, help_text='Échéancier ex: [{date: ..., amount: ...}]')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_categories', to='pedagogy.schoolyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='superadmin.tenant')),
            ],
            options={
                'verbose_name': 'Catégorie de frais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_reason', models.TextField(blank=True)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='finance.feecategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='pedagogy.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='superadmin.tenant')),
            ],
            options={
                'verbose_name': 'Frais élève',
                'unique_together': {('tenant', 'student', 'fee_category')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN MoMo'), ('WAVE', 'Wave'), ('BANK_TRANSFER', 'Virement bancaire'), ('CHECK', 'Chèque')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Référence transaction externe', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='COMPLETED', max_length=20)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_url', models.URLField(blank=True)),
                ('sms_notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pedagogy.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='superadmin.tenant')),
                ('student_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.studentfee')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payée'), ('OVERDUE', 'En retard')], default='PENDING', max_length=20)),
                ('pdf_url', models.URLField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='pedagogy.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='pedagogy.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='superadmin.tenant')),
            ],
            options={
                'verbose_name': 'Facture',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'student', 'school_year')},
            },
        ),
    ]
