# Generated by Django 5.1.4 on 2026-07-26 02:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('pedagogy', '0019_yearenddecision_non_nullable'),
        ('superadmin', '0002_tenant_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('ORANGE_MONEY', 'Orange Money')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], db_index=True, default='PENDING', max_length=20)),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('sms_notification_sent', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pedagogy.student')),
                ('student_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.studentfee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='superadmin.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status', 'payment_date'], name='finance_pay_tenant__ecf89b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_sequences', to='pedagogy.schoolyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='superadmin.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'school_year'), name='uq_receipt_sequence_per_tenant_year')],
            },
        ),
    ]
