# Generated by Django 5.1.4 on 2026-07-26 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_payment_receipt_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='receipt_pdf',
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_pdf_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
