# Generated by Django 5.1.4 on 2026-07-26 02:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_align_payment_amount_decimals_and_url'),
        ('superadmin', '0002_tenant_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrangeMoneyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_transaction_id', models.CharField(max_length=100, unique=True)),
                ('provider_status', models.CharField(choices=[('INITIATED', 'Initiée'), ('CONFIRMED', 'Confirmée'), ('FAILED', 'Échouée')], default='INITIATED', max_length=20)),
                ('raw_webhook_payload', models.JSONField(blank=True, default=dict)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orange_money_details', to='finance.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='superadmin.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
