# Generated by Django 5.1.4 on 2026-07-26 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_periodictask_reconcile_om'),
        ('pedagogy', '0019_yearenddecision_non_nullable'),
        ('superadmin', '0002_tenant_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_due', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PARTIAL', 'Partiellement payé'), ('PAID', 'Payé'), ('OVERDUE', 'En retard')], db_index=True, default='PENDING', max_length=10)),
                ('pdf_url', models.URLField(blank=True, max_length=500)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='pedagogy.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='pedagogy.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='superadmin.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='finance_inv_tenant__e82747_idx'), models.Index(fields=['tenant', 'student'], name='finance_inv_tenant__7ae6d3_idx')],
                'unique_together': {('tenant', 'student', 'school_year')},
            },
        ),
    ]
