# Generated by Django 5.1.6 on 2026-06-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('ADMIN_SCHOOL', 'Administrateur École'), ('NETWORK_ADMIN', 'Administrateur Réseau'), ('SECRETAIRE', 'Secrétaire'), ('ENSEIGNANT', 'Enseignant'), ('PARENT', 'Parent'), ('CUSTOM', 'Personnalisé')], max_length=50, unique=True),
        ),
    ]
