# Generated by Django 5.1.4 on 2026-08-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_backfill_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='access_end_date',
            field=models.DateField(blank=True, help_text='STAFF-V2-04 : compte inaccessible après cette date (mécanisme GUEST_TEACHER, vérifié au login).', null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='access_start_date',
            field=models.DateField(blank=True, help_text='STAFF-V2-04 : compte inaccessible avant cette date (mécanisme GUEST_TEACHER, vérifié au login).', null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('INSTITUTEUR_ADJOINT', 'Instituteur adjoint'), ('INSTITUTEUR', 'Instituteur'), ('PROFESSEUR_ADJOINT', "Professeur adjoint d'enseignement secondaire"), ('PROFESSEUR_ENS_SECONDAIRE', "Professeur d'enseignement secondaire"), ('PROFESSEUR_CERTIFIE', 'Professeur certifié')], max_length=30),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='statut_emploi',
            field=models.CharField(blank=True, choices=[('TITULAIRE', 'Titulaire'), ('CONTRACTUEL', 'Contractuel'), ('VACATAIRE', 'Vacataire')], max_length=15),
        ),
    ]
