# Generated by Django 5.1.4 on 2026-08-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Trouvé en marge de STAFF-V2-04 (repéré par `makemigrations`, sans lien
    avec ce ticket) : le champ `Role.name` n'avait jamais eu ses `choices`
    resynchronisées en migration depuis l'ajout d'ACCOUNTANT/CUSTOM au
    `TextChoices` du modèle — dérive purement cosmétique (métadonnées de
    validation Django, aucune donnée concernée), séparée de la migration
    STAFF-V2-04 pour ne pas mélanger les deux changements.
    """

    dependencies = [
        ('authentication', '0010_staffprofile_teacher_specifics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('DIRECTOR', 'Directeur'), ('STUDENT_STUDIES', 'Directeur des études / Scolarité'), ('TEACHER', 'Enseignant'), ('ACCOUNTANT', 'Comptable'), ('PARENT', "Parent d'élève"), ('CUSTOM', 'Personnalisé')], max_length=30, unique=True),
        ),
    ]
