# Generated by Django 5.1.4 on 2026-08-09 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_role_name_choices_drift'),
        ('superadmin', '0008_periodictask_flag_overdue_platform_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text="Null = rôle-modèle système, jamais assigné à un utilisateur réel (sert uniquement à cloner les permissions par défaut d'un nouveau tenant). SUPER_ADMIN est la seule exception assignée avec tenant=NULL.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='superadmin.tenant'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('DIRECTOR', 'Directeur'), ('STUDENT_STUDIES', 'Directeur des études / Scolarité'), ('TEACHER', 'Enseignant'), ('ACCOUNTANT', 'Comptable'), ('PARENT', "Parent d'élève"), ('CUSTOM', 'Personnalisé')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('name', 'CUSTOM'), _negated=True), fields=('tenant', 'name'), name='uniq_role_tenant_name_base'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('name', 'CUSTOM')), fields=('tenant', 'label'), name='uniq_role_tenant_label_custom'),
        ),
    ]
