# Generated by Django 5.1.6 on 2026-04-01 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée'), ('SUPERIEUR', 'Supérieur')], max_length=20)),
                ('name', models.CharField(help_text='Ex: 6ème, Terminale S', max_length=50)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='superadmin.tenant')),
            ],
            options={
                'verbose_name': 'Niveau',
                'ordering': ['cycle', 'order_index'],
                'unique_together': {('tenant', 'cycle', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: 2025-2026', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PREPARATION', 'En préparation'), ('OUVERTE', 'Ouverte aux inscriptions'), ('EN_COURS', 'En cours'), ('CLOTURE_EN_COURS', 'Clôture en cours'), ('CLOTUREE', 'Clôturée')], default='PREPARATION', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to='superadmin.tenant')),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-start_date'],
                'unique_together': {('tenant', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: 6ème A', max_length=100)),
                ('capacity', models.PositiveSmallIntegerField(default=60)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('main_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_classes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='superadmin.tenant')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='pedagogy.level')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='pedagogy.schoolyear')),
            ],
            options={
                'verbose_name': 'Classe',
                'ordering': ['school_year', 'level__order_index', 'name'],
                'unique_together': {('tenant', 'school_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(blank=True, max_length=20, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=150)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=150)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('tuteur_nom', models.CharField(max_length=200)),
                ('tuteur_telephone', models.CharField(help_text='Format: +224XXXXXXXXX', max_length=20)),
                ('tuteur_email', models.EmailField(blank=True, max_length=254)),
                ('tuteur_lien', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR', 'Tuteur légal'), ('AUTRE', 'Autre')], default='PERE', max_length=20)),
                ('contact_provisoire', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('TRANSFERE', 'Transféré'), ('SORTI', 'Sorti'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_students', to='pedagogy.schoolyear')),
                ('classe_actuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='pedagogy.class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_students', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='superadmin.tenant')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenom'],
                'unique_together': {('tenant', 'matricule')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SCIENTIFIC', 'Sciences'), ('LITERARY', 'Littéraire'), ('ARTISTIC', 'Artistique'), ('PHYSICAL', 'Éducation physique'), ('CIVIC', 'Éducation civique'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('is_official', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='superadmin.tenant')),
            ],
            options={
                'verbose_name': 'Matière',
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode', models.CharField(choices=[('TRIMESTRE_1', '1er Trimestre'), ('TRIMESTRE_2', '2e Trimestre'), ('TRIMESTRE_3', '3e Trimestre'), ('SEMESTRE_1', '1er Semestre'), ('SEMESTRE_2', '2e Semestre'), ('ANNUEL', 'Annuel')], max_length=15)),
                ('type_note', models.CharField(choices=[('DEVOIR', 'Devoir'), ('COMPOSITION', 'Composition'), ('EXAMEN', 'Examen'), ('ORAL', 'Oral')], default='DEVOIR', max_length=15)),
                ('note', models.DecimalField(decimal_places=2, help_text='Valeur brute saisie', max_digits=5)),
                ('note_sur', models.PositiveSmallIntegerField(default=20, help_text='Barème (ex: 20, 40, 100)')),
                ('note_convertie', models.DecimalField(decimal_places=2, editable=False, help_text='Calculé automatiquement : (note/note_sur)×20', max_digits=5)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('valide', models.BooleanField(default=False, help_text='False = brouillon')),
                ('justification_modification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saisie_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graded_by', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='superadmin.tenant')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='pedagogy.schoolyear')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='pedagogy.student')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='pedagogy.subject')),
            ],
            options={
                'verbose_name': 'Note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CC', 'Contrôle continu'), ('DS', 'Devoir surveillé'), ('TP', 'Travaux pratiques'), ('PARTICIPATION', 'Participation'), ('ORAL', 'Oral'), ('EXAMEN', 'Examen')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('max_score', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('date', models.DateField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='pedagogy.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='superadmin.tenant')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='pedagogy.subject')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('ABSENT_JUSTIFIED', 'Absent justifié'), ('LATE', 'En retard'), ('EXCLUDED', 'Exclu')], max_length=20)),
                ('minutes_late', models.PositiveSmallIntegerField(default=0)),
                ('justification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_attendances', to=settings.AUTH_USER_MODEL)),
                ('justified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justified_attendances', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='superadmin.tenant')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='pedagogy.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='pedagogy.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='pedagogy.subject')),
            ],
            options={
                'verbose_name': 'Présence',
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=50)),
                ('day_of_week', models.CharField(choices=[('1', 'Lundi'), ('2', 'Mardi'), ('3', 'Mercredi'), ('4', 'Jeudi'), ('5', 'Vendredi'), ('6', 'Samedi')], max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_recurring', models.BooleanField(default=True)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='pedagogy.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='pedagogy.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='superadmin.tenant')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_inscription', models.CharField(choices=[('NOUVELLE_INSCRIPTION', 'Nouvelle inscription'), ('REINSCRIPTION', 'Réinscription'), ('TRANSFERT_ENTRANT', 'Transfert entrant')], default='NOUVELLE_INSCRIPTION', max_length=25)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('frais_payes', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='pedagogy.class')),
                ('inscrit_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments_made', to=settings.AUTH_USER_MODEL)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='pedagogy.schoolyear')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='pedagogy.student')),
            ],
            options={
                'verbose_name': 'Inscription',
                'ordering': ['-date_inscription'],
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('weekly_hours', models.PositiveSmallIntegerField(default=0)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='pedagogy.class')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_subjects', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='pedagogy.subject')),
            ],
            options={
                'verbose_name': 'Matière de classe',
                'unique_together': {('classe', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='YearEndDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('ADMIS', 'Admis'), ('REDOUBLE', 'Redoublant'), ('ORIENTE', 'Orienté'), ('TRANSFERE', 'Transféré'), ('EXCLU', 'Exclu')], max_length=20)),
                ('moyenne_annuelle', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot immuable calculé au moment de la décision', max_digits=5, null=True)),
                ('mention', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('TRES_BIEN', 'Très Bien'), ('BIEN', 'Bien'), ('ASSEZ_BIEN', 'Assez Bien'), ('PASSABLE', 'Passable'), ('INSUFFISANT', 'Insuffisant')], max_length=20)),
                ('date_decision', models.DateField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_end_decisions', to='pedagogy.schoolyear')),
                ('classe_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_to', to='pedagogy.class')),
                ('classe_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions_from', to='pedagogy.class')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_end_decisions', to='pedagogy.student')),
                ('prise_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_end_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Décision de fin d'année",
                'ordering': ['-date_decision'],
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
    ]
