# Generated by Django 5.1.4 on 2026-07-20 00:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0002_tenant_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PREPARATION', 'Préparation'), ('ACTIVE', 'Active'), ('CLOSED', 'Clôturée')], default='PREPARATION', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='superadmin.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre')], default='TRIMESTRE', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('order', models.PositiveSmallIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='superadmin.tenant')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='pedagogy.schoolyear')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.UniqueConstraint(fields=('tenant', 'label'), name='uniq_schoolyear_label_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='academicperiod',
            constraint=models.UniqueConstraint(fields=('school_year', 'order'), name='uniq_period_order_per_year'),
        ),
    ]
