# Generated by Django 5.1.6 on 2026-04-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='type_note',
            field=models.CharField(choices=[('INTERROGATION', 'Interrogation'), ('DEVOIR', 'Devoir'), ('COMPOSITION', 'Composition'), ('EXAMEN', 'Examen'), ('ORAL', 'Oral')], default='DEVOIR', max_length=15),
        ),
    ]
