# Generated by Django 5.1.6 on 2026-05-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0002_alter_grade_type_note'),
        ('superadmin', '0003_add_campus_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='superadmin.campus', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='superadmin.campus', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='superadmin.campus', verbose_name='Campus'),
        ),
    ]
