# Generated by Django 5.1.4 on 2026-07-20 01:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0002_add_pedagogy_permissions'),
        ('superadmin', '0002_tenant_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('order_index', models.PositiveSmallIntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
    ]
