# Generated by Django 5.1.4 on 2026-07-20 01:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0005_subject_classsubject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='coefficient',
            field=models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('99.9'))]),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='weekly_hours',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('99.9'))]),
        ),
    ]
