# Generated by Django 5.1.6 on 2026-06-19 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0005_add_filiere'),
        ('superadmin', '0007_tenant_school_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('tenant', 'code')},
        ),
    ]
