# Generated by Django 5.1.6 on 2026-06-28 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0006_alter_filiere_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_mixed',
            field=models.BooleanField(default=False, verbose_name='Classe mixte'),
        ),
        migrations.CreateModel(
            name='MixedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mixte', models.CharField(choices=[('ALTERNATE_DAY', 'Alternance jour par jour'), ('ALTERNATE_WEEK', 'Alternance semaine par semaine'), ('ALTERNATE_HALF_DAY', 'Alternance demi-journée'), ('SIMULTANEOUS', 'Simultané (moniteur)')], default='ALTERNATE_DAY', max_length=30, verbose_name='Type de mixité')),
                ('repartition', models.JSONField(blank=True, default=dict, help_text="Répartition du temps d'enseignement par niveau (JSON)", verbose_name='Répartition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe_physique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mixed_config', to='pedagogy.class', verbose_name='Classe physique')),
            ],
            options={
                'verbose_name': 'Classe mixte',
                'verbose_name_plural': 'Classes mixtes',
            },
        ),
        migrations.CreateModel(
            name='MixedClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacite', models.PositiveSmallIntegerField(default=30, verbose_name='Capacité par niveau')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogy.level', verbose_name='Niveau supplémentaire')),
                ('mixed_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='pedagogy.mixedclass', verbose_name='Classe mixte')),
            ],
            options={
                'verbose_name': 'Niveau de classe mixte',
                'verbose_name_plural': 'Niveaux de classe mixte',
                'ordering': ['ordre'],
                'unique_together': {('mixed_class', 'level')},
            },
        ),
    ]
