# Generated by Django 5.1.4 on 2026-07-20 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0006_alter_classsubject_coefficient_and_more'),
        ('superadmin', '0002_tenant_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matricule', models.CharField(db_index=True, max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=150)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=150)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('photo', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('TRANSFERE', 'Transféré'), ('SORTI', 'Sorti'), ('ARCHIVE', 'Archivé')], db_index=True, default='ACTIF', max_length=20)),
                ('annee_inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students_first_enrolled', to='pedagogy.schoolyear')),
                ('classe_actuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='pedagogy.schoolclass')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='superadmin.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_inscription', models.CharField(choices=[('NOUVELLE_INSCRIPTION', 'Nouvelle inscription'), ('REINSCRIPTION', 'Réinscription'), ('TRANSFERT_ENTRANT', 'Transfert entrant')], max_length=25)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='pedagogy.schoolclass')),
                ('inscrit_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_created', to=settings.AUTH_USER_MODEL)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='pedagogy.schoolyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='superadmin.tenant')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='pedagogy.student')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculeSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricule_sequences', to='pedagogy.schoolyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='superadmin.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'school_year'), name='uniq_matricule_sequence_per_year')],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'statut'], name='pedagogy_st_tenant__2a5ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['nom', 'prenom', 'date_naissance'], name='pedagogy_st_nom_8a8447_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('tenant', 'matricule'), name='uniq_matricule_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'school_year'), name='uniq_enrollment_per_year'),
        ),
    ]
