# Generated by Django 5.1.6 on 2026-06-28 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0007_add_mixed_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='niveau_mixte',
            field=models.ForeignKey(blank=True, help_text="Niveau spécifique de l'élève au sein d'une classe mixte", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixed_enrollments', to='pedagogy.level', verbose_name='Niveau dans la classe mixte'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='mixed_level',
            field=models.ForeignKey(blank=True, help_text='Niveau concerné pour les classes mixtes à alternance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='pedagogy.level', verbose_name='Niveau (classe mixte)'),
        ),
    ]
