# Generated by Django 5.1.6 on 2026-06-28 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0008_add_mixed_enrollment_level'),
        ('superadmin', '0007_tenant_school_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('LANGUE', 'Groupe de langue')], max_length=10, verbose_name='Type de groupe')),
                ('name', models.CharField(help_text='Ex: TD1, Groupe A', max_length=100)),
                ('capacite', models.PositiveSmallIntegerField(default=30)),
                ('horaire_specifique', models.JSONField(blank=True, default=dict, help_text='Horaire optionnel du groupe (jour, début, fin, salle)', verbose_name='Horaire spécifique')),
                ('classe_mere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='pedagogy.class')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='superadmin.tenant')),
            ],
            options={
                'verbose_name': 'Groupe de classe',
                'verbose_name_plural': 'Groupes de classe',
                'ordering': ['classe_mere', 'type', 'name'],
                'unique_together': {('tenant', 'classe_mere', 'name')},
            },
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Groupe associé pour les créneaux de TD, TP ou langue', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='pedagogy.classgroup', verbose_name='Groupe (TD/TP/Langue)'),
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NIVEAU_COMBINE', 'Niveaux combinés'), ('FILIERE_PARTAGEE', 'Filière partagée')], max_length=20, verbose_name='Type de sous-groupe')),
                ('name', models.CharField(help_text='Ex: Groupe inter-niveaux, Sciences', max_length=100)),
                ('capacite', models.PositiveSmallIntegerField(default=30)),
                ('classes', models.ManyToManyField(related_name='subgroups', to='pedagogy.class')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroups', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='superadmin.tenant')),
            ],
            options={
                'verbose_name': 'Sous-groupe',
                'verbose_name_plural': 'Sous-groupes',
                'ordering': ['tenant', 'type', 'name'],
            },
        ),
    ]
