# Generated by Django 5.1.4 on 2026-07-20 22:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0010_add_eleves_read_update_permissions'),
        ('superadmin', '0002_tenant_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('ABSENT_JUSTIFIE', 'Absent justifié'), ('RETARD', 'Retard')], max_length=20)),
                ('minutes_late', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('justification_text', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='pedagogy.schoolclass')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='pedagogy.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='superadmin.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['classe', 'date'], name='pedagogy_at_classe__6b6ade_idx'), models.Index(fields=['tenant', 'created_at'], name='pedagogy_at_tenant__3d2556_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='uniq_attendance_per_student_per_day')],
            },
        ),
    ]
