# Generated by Django 5.1.4 on 2026-07-21 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0016_add_notes_permissions'),
        ('superadmin', '0002_tenant_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearEndDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('ADMIS', 'Admis'), ('REDOUBLE', 'Redouble'), ('EXCLU', 'Exclu')], max_length=20)),
                ('moyenne_annuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('classe_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_end_decisions_destination', to='pedagogy.schoolclass')),
                ('prise_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_end_decisions_made', to=settings.AUTH_USER_MODEL)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_end_decisions', to='pedagogy.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_end_decisions', to='pedagogy.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='superadmin.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'school_year', 'decision'], name='pedagogy_ye_tenant__3cef43_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'school_year'), name='uniq_decision_per_student_per_year')],
            },
        ),
    ]
