# Generated by Django 5.1.4 on 2026-07-21 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0017_yearenddecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearenddecision',
            name='classe_origine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions_from', to='pedagogy.schoolclass'),
        ),
        migrations.AddField(
            model_name='yearenddecision',
            name='date_decision',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
