# Generated by Django 5.1.4 on 2026-07-21 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0018_yearenddecision_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearenddecision',
            name='classe_origine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions_from', to='pedagogy.schoolclass'),
        ),
        migrations.AlterField(
            model_name='yearenddecision',
            name='date_decision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='yearenddecision',
            name='moyenne_annuelle',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
