# Generated by Django 5.1.6 on 2026-04-13 12:34

import apps.support.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolOnboardingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_code', models.CharField(default=apps.support.models.generate_tracking_code, max_length=20, unique=True)),
                ('school_name', models.CharField(max_length=255)),
                ('school_type', models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée'), ('MIXTE', 'Mixte')], max_length=20)),
                ('school_city', models.CharField(blank=True, max_length=120)),
                ('school_phone', models.CharField(blank=True, max_length=20)),
                ('school_email', models.EmailField(max_length=254)),
                ('admin_first_name', models.CharField(max_length=120)),
                ('admin_last_name', models.CharField(max_length=120)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_phone', models.CharField(blank=True, max_length=20)),
                ('admin_password_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_onboarding_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'ouverture d'école",
                'verbose_name_plural': "Demandes d'ouverture d'école",
                'ordering': ['-created_at'],
            },
        ),
    ]
