# Generated by Django 5.1.6 on 2026-04-01 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], max_length=50, unique=True)),
                ('max_students', models.PositiveIntegerField(default=500)),
                ('max_staff', models.PositiveIntegerField(default=50)),
                ('modules_activated', models.JSONField(default=list, help_text="Liste des modules activés ex: ['pedagogy','finance']")),
                ('storage_max_gb', models.PositiveIntegerField(default=10, verbose_name='Stockage max (Go)')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_annual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'école")),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('code_minedu', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code MEN (MINEDU)')),
                ('type', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVE', 'Privé'), ('COMMUNAUTAIRE', 'Communautaire'), ('CONFESSIONNEL', 'Confessionnel')], default='PRIVE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Essai'), ('SUSPENDED', 'Suspendue'), ('CANCELLED', 'Annulée')], default='TRIAL', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, help_text="Configuration spécifique à l'école (seuils, périodes, etc.)")),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='superadmin.plan', verbose_name="Plan d'abonnement")),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TRIAL', 'Essai'), ('ACTIVE', 'Active'), ('PAST_DUE', 'En retard'), ('SUSPENDED', 'Suspendue'), ('CANCELLED', 'Annulée')], default='TRIAL', max_length=20)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='superadmin.plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='superadmin.tenant')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
    ]
