# Generated by Django 5.1.6 on 2026-04-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée'), ('MIXTE', 'Mixte')], default='PRIVE', max_length=20),
        ),
    ]
