# Generated by Django 5.1.6 on 2026-05-28 18:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_update_tenant_type_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du campus')),
                ('address', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('prefecture', models.CharField(blank=True, max_length=100, verbose_name='Préfecture')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('active_levels', models.JSONField(blank=True, default=list, help_text="Cycles actifs sur ce campus ex: ['PRIMAIRE', 'COLLEGE']", verbose_name='Niveaux activés')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_main', models.BooleanField(default=False, help_text="Le campus principal est le siège de l'établissement.", verbose_name='Campus principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='superadmin.tenant', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
                'ordering': ['-is_main', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
