# Generated by Django 5.1.6 on 2026-06-01 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_add_campus_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du réseau')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_networks', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur du réseau')),
            ],
            options={
                'verbose_name': "Réseau d'écoles",
                'verbose_name_plural': "Réseaux d'écoles",
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='superadmin.tenantnetwork', verbose_name="Réseau d'écoles"),
        ),
    ]
