# Generated by Django 5.1.4 on 2026-07-31 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_tenant_suspension_soft_hard'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_seq', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_name', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('issued_date', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('OVERDUE', 'En retard')], db_index=True, default='PENDING', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_invoices', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='superadmin__tenant__f9b976_idx')],
            },
        ),
    ]
