# Generated by Django 5.1.4 on 2026-07-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_periodictask_generate_platform_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_cycle_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
