# Generated by Django 5.1.6 on 2026-06-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_plan_advanced_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='school_type',
            field=models.CharField(choices=[('PUB', 'Publique'), ('PRIV', 'Privée'), ('FRAR', 'FRAR (Fonds de Roulement)'), ('ETP', 'École de Travail Professionnel'), ('ETPR', 'École Technique Privée'), ('INT', 'Internationale'), ('COM', 'Communautaire'), ('INC', 'Independente')], default='PRIV', help_text='PUB = École publique (pas de module paie), PRIV = Privée', max_length=10, verbose_name="Type d'établissement"),
        ),
    ]
