# Generated by Django 5.1.4 on 2026-08-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_tenant_billing_cycle_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminvoice',
            name='last_reminder_stage',
            field=models.CharField(blank=True, choices=[('OVERDUE', 'Retard initial (J+1)'), ('D7', 'Relance J+7'), ('D15', 'Suspension lecture seule J+15'), ('D30', 'Suspension totale J+30')], default='', max_length=10),
        ),
    ]
